### PR TITLE
Change "TNT" textures.

### PR DESCRIPTION
**Pull request by kingoscargames**

### CODE REVIEW

**Comment by Gerold55** [comment]
Lighten up the textures a little bit

**Comment by kingoscargames** [comment]
> Lighten up the textures a little bit

I did.

**Comment by Gerold55** [comment]
They look really good :) 
We are trying to make it unique but have colors of Minecraft is why I had asked if you were able to lighten them up :)

**Comment by kingoscargames** [comment]
> They look really good :)

Thanks

> We are trying to make it unique but have colors of Minecraft is why I had asked if you were able to lighten them up :)

I know, i was told like 4 times. XD

**Comment by Gerold55** [comment]
Oh yeah lol (;

**Pull request merged**
